# Generated by Django 4.2 on 2023-04-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appInstanceId', models.CharField(default='unverified', max_length=64)),
                ('trafficRuleId', models.CharField(default='unverified', max_length=64)),
                ('filterType', models.CharField(default='unverified', max_length=64)),
                ('priority', models.CharField(default='unverified', max_length=64)),
                ('trafficFilter', models.CharField(default='unverified', max_length=64)),
                ('action', models.CharField(default='unverified', max_length=64)),
                ('dstInterface', models.CharField(default='unverified', max_length=64)),
                ('state', models.CharField(default='unverified', max_length=64)),
            ],
        ),
    ]
