# Generated by Django 4.2 on 2023-05-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0002_trafficrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppTerminationNotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appInstanceId', models.CharField(default='unverified', max_length=64)),
                ('subscriptionType', models.CharField(default='unverified', max_length=64)),
                ('callbackReference', models.CharField(default='unverified', max_length=64)),
                ('_links', models.CharField(default='unverified', max_length=64)),
                ('self_referring_URI', models.CharField(default='unverified', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='DstInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dstInterface_UUID', models.CharField(default='unverified', max_length=64)),
                ('interfaceType', models.CharField(default='unverified', max_length=64)),
                ('tunnelType', models.CharField(default='unverified', max_length=64)),
                ('tunnelDstAddress', models.CharField(default='unverified', max_length=64)),
                ('tunnelSrcAddress', models.CharField(default='unverified', max_length=64)),
                ('srcMacAddress', models.CharField(default='unverified', max_length=64)),
                ('dstMacAddress', models.CharField(default='unverified', max_length=64)),
                ('dstIpAddress', models.CharField(default='unverified', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trafficFilter_UUID', models.CharField(default='unverified', max_length=64)),
                ('srcAddress', models.CharField(default='unverified', max_length=64)),
                ('dstAddress', models.CharField(default='unverified', max_length=64)),
                ('srcPort', models.CharField(default='unverified', max_length=64)),
                ('dstPort', models.CharField(default='unverified', max_length=64)),
                ('protocol', models.CharField(default='unverified', max_length=64)),
                ('token', models.CharField(default='unverified', max_length=64)),
                ('srcTunnelAddress', models.CharField(default='unverified', max_length=64)),
                ('tgtTunnelAddress', models.CharField(default='unverified', max_length=64)),
                ('srcTunnelPort', models.CharField(default='unverified', max_length=64)),
                ('dstTunnelPort', models.CharField(default='unverified', max_length=64)),
                ('qCI', models.CharField(default='unverified', max_length=64)),
                ('dSCP', models.CharField(default='unverified', max_length=64)),
                ('tC', models.CharField(default='unverified', max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='trafficrule',
            old_name='dstInterface',
            new_name='dstInterface_UUID',
        ),
        migrations.RenameField(
            model_name='trafficrule',
            old_name='trafficFilter',
            new_name='trafficFilter_UUID',
        ),
    ]
